# action.yml
name: 'TaintImpact'
description: 'Run TaintImpact on this branch and master.'
inputs:
  config-command:
    description: 'The command to configure the build. E.g. cmake...'
    required: false
  build-command: 
    description: 'The command to build the project. E.g. make'
    required: true
  execute-command:
    description: "The command to execute the program."
    required: true
  clean-command:
    description: 'The command to clean up build files. Eg make clean'
    required: false
  default-branch:
    description: "The default branch of the repository."
    required: false
    default: "master"
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config-command }}
    - ${{ inputs.build-command }}
    - ${{ inputs.execute-command }}   
    - ${{ inputs.clean-command }}
