# action.yml
name: 'TaintImpact'
description: 'Run TaintImpact on this branch and master.'
inputs:
  who-to-greet:  # id of input
    description: 'File to execute'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
